/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youthopiasherlockedquiz;

import java.io.File;
import java.util.Random;
import javax.swing.JOptionPane;
import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author hj101
 */
public class Riddle extends javax.swing.JFrame {

    static int[] id = {0, 1};
    static String[] Ques = {"1+1", "2+2"};
    static String[] CAns = {"2", "4"};
    static String[] Ans2 = {"3", "5"};
    static String[] Ans3 = {"7", "9"};
    static String[] Ans4 = {"6", "8"};
    static String[] ans = {"1", "2", "3", "4"};
    static final String corr = "QuizCorrect.mp3";
    MP3Player mp3playerCorr = new MP3Player(new File(corr));
    static final String incorr = "QuizIncorrect.mp3";
    MP3Player mp3playerIncorr = new MP3Player(new File(incorr));
    static String[] AnsIn = new String[2];
    static int i = -1;
    int time=120;
    
    public void update1() {
        
        
    
        i = AdminPanel.indexID;
        System.out.print(id[0]);
        Random rand = new Random();
        int rand1 = rand.nextInt(4);
        //  int ansIndex;
        txt_Ques.setText(Ques[i]);

        switch (rand1) {
            case 0:
                RadBut1.setText(CAns[i]);
                RadBut2.setText(Ans2[i]);
                RadBut3.setText(Ans3[i]);
                RadBut4.setText(Ans4[i]);
                break;
            case 1:
                RadBut4.setText(CAns[i]);
                RadBut2.setText(Ans2[i]);
                RadBut3.setText(Ans3[i]);
                RadBut1.setText(Ans4[i]);
                break;
            case 2:
                RadBut3.setText(CAns[i]);
                RadBut4.setText(Ans2[i]);
                RadBut2.setText(Ans3[i]);
                RadBut1.setText(Ans4[i]);
                break;
            case 3:
                RadBut2.setText(CAns[i]);
                RadBut4.setText(Ans2[i]);
                RadBut1.setText(Ans3[i]);
                RadBut3.setText(Ans4[i]);
                break;
            default:
                break;
        }

    }

    /**
     * Creates new form Quiz
     */
    public Riddle() {
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                
                txt_Time.setText("time left-"+time/60+"min"+time%60+" sec");
                time--;
            }
        });
        timer.start();
      //  setUndecorated(true);
        //this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        initComponents();
        update1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        txt_Top = new javax.swing.JLabel();
        RadBut1 = new javax.swing.JRadioButton();
        RadBut3 = new javax.swing.JRadioButton();
        RadBut2 = new javax.swing.JRadioButton();
        RadBut4 = new javax.swing.JRadioButton();
        txt_Ques = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        txt_Time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_Top.setBackground(new java.awt.Color(255, 255, 255));
        txt_Top.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_Top.setText("Enter the answer");

        RadBut1.setText("But 1");
        RadBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBut1ActionPerformed(evt);
            }
        });

        RadBut3.setText("But 3");
        RadBut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBut3ActionPerformed(evt);
            }
        });

        RadBut2.setText("But 2");
        RadBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBut2ActionPerformed(evt);
            }
        });

        RadBut4.setText("But 4");
        RadBut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBut4ActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Admin.setText("jButton1");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        txt_Time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadBut1)
                    .addComponent(RadBut3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadBut4)
                    .addComponent(RadBut2))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Top)
                            .addComponent(txt_Ques)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(383, 383, 383))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txt_Top)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Ques)
                .addGap(48, 48, 48)
                .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadBut1)
                    .addComponent(RadBut2))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadBut3)
                    .addComponent(RadBut4))
                .addGap(35, 35, 35)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBut1ActionPerformed
        if (RadBut1.isSelected()) {
            RadBut2.setSelected(false);
            RadBut3.setSelected(false);
            RadBut4.setSelected(false);
            AnsIn[i] = RadBut1.getText();
        }
    }//GEN-LAST:event_RadBut1ActionPerformed

    private void RadBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBut2ActionPerformed
        if (RadBut2.isSelected()) {
            RadBut1.setSelected(false);
            RadBut3.setSelected(false);
            RadBut4.setSelected(false);
            AnsIn[i] = RadBut2.getText();
        }
    }//GEN-LAST:event_RadBut2ActionPerformed

    private void RadBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBut3ActionPerformed
        if (RadBut3.isSelected()) {
            RadBut2.setSelected(false);
            RadBut1.setSelected(false);
            RadBut4.setSelected(false);
            AnsIn[i] = RadBut3.getText();
        }
    }//GEN-LAST:event_RadBut3ActionPerformed

    private void RadBut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBut4ActionPerformed
        if (RadBut4.isSelected()) {
            RadBut2.setSelected(false);
            RadBut3.setSelected(false);
            RadBut1.setSelected(false);
            AnsIn[i] = RadBut4.getText();
        }
    }//GEN-LAST:event_RadBut4ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        if (AnsIn[i].equals(CAns[i])) {
            mp3playerCorr.play();
            this.dispose();
            PinEntry_1.main(new String[0]);
            JOptionPane.showMessageDialog(null, "Correct Answer !\n The door is unlocked.");
            update1();
            mp3playerCorr.stop();
        } else {
            mp3playerIncorr.play();
            JOptionPane.showMessageDialog(null, "Pssswords didn't Matched !\nYou are out of the Game.", "Game Over", JOptionPane.ERROR_MESSAGE);
            mp3playerIncorr.stop();
            this.dispose();
            PinEntry_1.main(new String[0]);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        this.dispose();
        AdminPanel.main(new String[0]);
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riddle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riddle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riddle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riddle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Riddle().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JRadioButton RadBut1;
    private javax.swing.JRadioButton RadBut2;
    private javax.swing.JRadioButton RadBut3;
    private javax.swing.JRadioButton RadBut4;
    private javax.swing.JButton Submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel txt_Ques;
    private javax.swing.JLabel txt_Time;
    private javax.swing.JLabel txt_Top;
    // End of variables declaration//GEN-END:variables
}
